Repository pasqal-io/maximum-independent-set, pull requests merged in 2025-06, with the labels that each got.

#42 [Fix] Infinite loop in preprocessing
  mis/pipeline/kernelization.py
Labels: bug

#39 Added a 3SAT Solver example
  .pre-commit-config.yaml
  examples/Tutorial 4 - 3SAT Solver.ipynb
Labels: unitary hack

#48 [Infra] Add config file for Renovate bot.
  renovate.json
Labels: infra

#50 [Infra] Configure renovate
  renovate.json
Labels: infra

#40 Added a Tutorial for a graph coloring solver
  examples/Tutorial 5 - Graph Coloring Solver.ipynb
  examples/datasets/coloring/antenna_Paris.csv
  examples/datasets/coloring/counterexample_1.csv
  mis/coloring/__init__.py
  mis/coloring/coloring.py
  mis/data/__init__.py
  mis/data/dataloader.py
  pyproject.toml
Labels: unitary hack

#69 [Cleanup] Removing some dead code
  pyproject.toml
  scripts/before_tests.py
Labels: enhancement

#71 [Release] Bump version for release.
  pyproject.toml
Labels: release
